<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="91" />
      <entry action="$Cut" count="1" />
      <entry action="$Delete" count="136" />
      <entry action="$Paste" count="1040" />
      <entry action="$SelectAll" count="295" />
      <entry action="$Undo" count="4436" />
      <entry action="ActivateTerminalToolWindow" count="20" />
      <entry action="Back" count="39" />
      <entry action="Bitbucket.CreatePullRequest" count="2" />
      <entry action="Bitbucket.CreateSnippet" count="4" />
      <entry action="Change JavaScript language version" count="1" />
      <entry action="ChangesView.CreatePatchFromChanges" count="1" />
      <entry action="ChangesView.Refresh" count="1" />
      <entry action="ChangesView.Revert" count="1" />
      <entry action="CheckinFiles" count="27" />
      <entry action="CheckinProject" count="10" />
      <entry action="CloseAllEditors" count="40" />
      <entry action="CloseAllEditorsButActive" count="9" />
      <entry action="CodeCompletion" count="1" />
      <entry action="CollapseRegion" count="3" />
      <entry action="CopyElement" count="12" />
      <entry action="CreateVueSingleFileComp" count="3" />
      <entry action="Cvs.Add" count="3" />
      <entry action="Cvs.ToggleOffline" count="3" />
      <entry action="EditSource" count="1" />
      <entry action="EditorBackSpace" count="22613" />
      <entry action="EditorChooseLookupItem" count="83" />
      <entry action="EditorChooseLookupItemReplace" count="2041" />
      <entry action="EditorCodeBlockStart" count="1" />
      <entry action="EditorCopy" count="2345" />
      <entry action="EditorCut" count="7" />
      <entry action="EditorDelete" count="4" />
      <entry action="EditorDeleteLine" count="25" />
      <entry action="EditorDeleteToWordStart" count="1" />
      <entry action="EditorDown" count="3856" />
      <entry action="EditorDuplicate" count="10" />
      <entry action="EditorEnter" count="3386" />
      <entry action="EditorEscape" count="69" />
      <entry action="EditorGutterToggleGlobalLineNumbers" count="1" />
      <entry action="EditorLeft" count="8391" />
      <entry action="EditorLineEnd" count="1" />
      <entry action="EditorLineStart" count="2" />
      <entry action="EditorPaste" count="2603" />
      <entry action="EditorPasteFromX11" count="3" />
      <entry action="EditorPreviousWord" count="2" />
      <entry action="EditorRight" count="12044" />
      <entry action="EditorSelectWord" count="9" />
      <entry action="EditorSplitLine" count="3" />
      <entry action="EditorStartNewLine" count="10" />
      <entry action="EditorTab" count="96" />
      <entry action="EditorToggleInsertState" count="22" />
      <entry action="EditorUp" count="1520" />
      <entry action="ExpandAllRegions" count="1" />
      <entry action="FileChooser.GotoDesktop" count="1" />
      <entry action="FileChooser.GotoHome" count="2" />
      <entry action="FileChooser.GotoProject" count="1" />
      <entry action="FileChooser.Refresh" count="3" />
      <entry action="FileChooser.ShowHiddens" count="1" />
      <entry action="Find" count="155" />
      <entry action="FindNext" count="5" />
      <entry action="FindPrevious" count="1" />
      <entry action="Git.Add" count="27" />
      <entry action="Git.Branches" count="1" />
      <entry action="Github.Create.Gist" count="1" />
      <entry action="GotoBookmark2" count="3" />
      <entry action="GotoBookmark4" count="3" />
      <entry action="GotoBookmark9" count="1" />
      <entry action="GotoDeclaration" count="3" />
      <entry action="GotoLine" count="2" />
      <entry action="HideAllWindows" count="298" />
      <entry action="IdeScriptingConsole" count="2" />
      <entry action="IntroduceParameter" count="2" />
      <entry action="JumpToLastWindow" count="3" />
      <entry action="NewDir" count="111" />
      <entry action="NewDirectoryProject" count="7" />
      <entry action="NewFile" count="3" />
      <entry action="NewHtmlFile" count="1" />
      <entry action="NewJavaScriptFile" count="7" />
      <entry action="NewTypeScriptConfigFile" count="1" />
      <entry action="OpenDirectoryProject" count="4" />
      <entry action="OpenFile" count="17" />
      <entry action="OptimizeImports" count="4" />
      <entry action="ParameterInfo" count="2" />
      <entry action="PasteMultiple" count="1" />
      <entry action="PhpListenDebugAction" count="2" />
      <entry action="PhpNewClass" count="24" />
      <entry action="PhpNewFile" count="9" />
      <entry action="PublishGroup.Download" count="36" />
      <entry action="PublishGroup.SyncLocalVsRemote" count="26" />
      <entry action="PublishGroup.Upload" count="91" />
      <entry action="PublishGroup.UploadTo" count="1" />
      <entry action="Register" count="2" />
      <entry action="RemoteHostView.CreateFolder" count="1" />
      <entry action="RemoteHostView.Rename" count="5" />
      <entry action="RemoteHostView.SetPermissions" count="9" />
      <entry action="RenameElement" count="68" />
      <entry action="RestoreDefaultLayout" count="1" />
      <entry action="Resume" count="1" />
      <entry action="RevealIn" count="73" />
      <entry action="RunClass" count="1" />
      <entry action="SaveAll" count="6759" />
      <entry action="ScopeView.EditScopes" count="1" />
      <entry action="SearchEverywhere" count="5" />
      <entry action="ShowFilePath" count="1" />
      <entry action="ShowGutterIconsSettings" count="2" />
      <entry action="ShowProcessWindow" count="1" />
      <entry action="ShowSettings" count="30" />
      <entry action="SplitVertically" count="1" />
      <entry action="Start.Use.Vcs" count="1" />
      <entry action="StoreDefaultLayout" count="1" />
      <entry action="SynchronizeCurrentFile" count="3" />
      <entry action="ToggleBookmark" count="14" />
      <entry action="ToggleLineBreakpoint" count="86" />
      <entry action="UnmarkTestSourceRoot" count="1" />
      <entry action="Vcs.CopyRevisionNumberAction" count="1" />
      <entry action="Vcs.Push" count="1" />
      <entry action="Vcs.QuickListPopupAction" count="1" />
      <entry action="Vcs.RefreshStatuses" count="1" />
      <entry action="Vcs.RollbackChangedLines" count="1" />
      <entry action="Vcs.ShowTabbedFileHistory" count="1" />
      <entry action="Vcs.UpdateProject" count="2" />
      <entry action="WebDeployment.BrowseServers" count="23" />
      <entry action="WebDeployment.Configuration" count="28" />
      <entry action="WebDeployment.ToggleAutoUpload" count="11" />
    </counts>
  </component>
</application>